# Generated by Django 5.0.5 on 2024-05-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cliente_value_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
