# Generated by Django 5.0.5 on 2024-05-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cliente_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
