# Generated by Django 5.0.5 on 2024-05-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_funcionario_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
