# Generated by Django 5.0.5 on 2024-05-15 18:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_teste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teste',
            new_name='RegistroFinanceiro',
        ),
    ]
