# Generated by Django 5.0.5 on 2024-05-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_teste_registrofinanceiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofinanceiro',
            name='category',
            field=models.CharField(choices=[('cliente', 'cliente'), ('custo', 'custo'), ('funcionario', 'funcionario')], max_length=200),
        ),
    ]
