# Generated by Django 5.0.5 on 2024-05-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cardapio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofinanceiro',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
