# Generated by Django 5.0.5 on 2024-05-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_registrofinanceiro_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
