# Generated by Django 5.0.5 on 2024-05-22 22:40

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_cardapio_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofinanceiro',
            name='value',
            field=models.FloatField(validators=[main.models.validate_positive]),
        ),
    ]
