# Generated by Django 5.0.3 on 2024-09-25 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_registrofinanceiro_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofinanceiro',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
